name: Test

on: push

jobs:
  install:
    name: Install check-codeowners and show help
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - name: Install check-codeowners
        uses: ./
      - name: Show help
        run: check-codeowners --help
