name: Test

on: push

jobs:
  test:
    name: rspec
    runs-on: [ self-hosted, zendesk-stable ]
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-ruby@v1.48.0
        with:
          bundler-cache: true
      - run: bundle exec rspec -f d
  install:
    name: Install check-codeowners and show help
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - name: Install check-codeowners
        uses: ./
      - name: Show help
        run: check-codeowners --help
