name: Test

on: push

jobs:
  no_diff:
    name: Check no-diff from build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: ruby script/no-diff.rb
  test:
    name: rspec
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.6' # this is EOL but is what comes shipped on every mac, so we need to support it
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec -f d
  install:
    name: Install check-codeowners and show help
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install check-codeowners
        uses: ./
      - name: Show help
        run: check-codeowners --help
