name: Test

on: push

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec standardrb
  test:
    name: rspec
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rspec -f d
  install:
    name: Install check-codeowners and show help
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - name: Install check-codeowners
        uses: ./
      - name: Show help
        run: check-codeowners --help
